# Generated by Django 5.1.2 on 2024-11-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sign',
            field=models.IntegerField(default=2),
        ),
    ]
