# Generated by Django 5.1.2 on 2024-11-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sign',
            field=models.IntegerField(default=3),
        ),
    ]
