# Generated by Django 5.0.3 on 2024-11-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('educational_background', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('tech_stack', models.CharField(max_length=100)),
            ],
        ),
    ]
